train_path: "../rnd_minigrid/run_atari.py"
main:
  env: MiniGrid-Empty-6x6-v0
  gamma_ext: 0.999
  max_eprews: 0.93
  num-timesteps: 5.e+6
  max_episode_steps: 400
  int_coeff: 1.0
  ext_coeff: 0.
  proportion_of_exp_used_for_predictor_update: 0.25
