main:
  env: ["MiniGrid-Empty-16x16-v0",
        "MiniGrid-DoorKey-8x8-v0", "MiniGrid-DoorKey-16x16-v0",
        "MiniGrid-MultiRoom-N2-S4-v0", "MiniGrid-MultiRoom-N6-v0",
        "MiniGrid-BlockedUnlockPickup-v0",
        "MiniGrid-ObstructedMaze-1Dlh-v0", "MiniGrid-ObstructedMaze-1Dlhb-v0"
        'MiniGrid-MemoryS11-v0']
agent:
  norm_iR_rnd_style: [true, false]
  train_ap_cross_e_gap: [true, false]
  pred_state_rnn_mode: [true, false]
