env_cfg:
  wrapper: [[aux_in_rel_pos, full_state_train, constant_reward, just_move],
  [aux_in_goal_pos, full_state_train, constant_reward, just_move],
  [aux_in_agent_pos, full_state_train, constant_reward, just_move]]

  env_args:
    goal_rand_offset: [0,1,2,3]